server:
  port: 8082

spring:
  application:
    name: nacos-service-register-consumer8082
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-producer-service: nacos-service-register-producer8081
  interfaceName: producer/getProducerInfo
